export const customer = {
    companyName:["Addis Ababa Housing Development Corporation","","","","",""],
    customer:["Customer","","","","",""],
    checkStatus:["Check status","","","","",""],
    makeAccusation:["Make Accusation","","","","",""],
    name:["Name","","","","",""],
    subject:["Subject","","","","",""],
    phone:["Phone","","","","",""],
    description:["Description","","","","",""],
    attachement:["Attachement","","","","",""],
    cancel:["Cancel","","","","",""],
    submit:["Submit","","","","",""],
    login:["Login","","","","",""],
    register:["Register","","","",""],
    bannerTitle: ["Welcome To Addis Ababa Housing Development Corporation","","","","",""],
    bannerSubTitle:["Customer Service","","","","",""],
    services:["Services","","","","",""],
    division1:["Land Design and Infrastructure Development","","","","",""],
    division2:["House Construction","","","",""],
    division3:["House Transfer and Construction Finance","","","","",""],
    division4:["Corporate Service","","","","",""],
    logintoyourAccount:["Login to your account","","","","",""],
    usernamePlaceholder:["Username","","","","",""],
    passwordPlaceholder:["password","","","","",""],
    forgotPasswordLink:["forgot your password","","","","",""],
    loginButton:["Sign In","","","","",""],
    createAnAccount:["Create An Account","","","","",""],
    firstname:["First Name","","","","",""],
    middlename:["Middle Name","","","","",""],
    lastname:["Last Name","","","","",""],
    username:["Username","","","","",""],
    email:["Email","","","","",""],
    subCity:["Sub-city","","","","",""],
    woreda:["Woreda","","","","",""],
    gender:["Gender","","","","",""],
    male:["Male","","","","",""],
    female:["Female","","","","",""],
    password:["Password","","","","",""],
    confirmPassword:["Confirm Password","","","","",""],
    uploadProfileImage:["Upload Profile Image","","","","",""],
    verifyYourEmail:["Verify your Email","","","","",""],
    weHaveSentACode:["We have sent a code to your email","","","","",""],
    verifyEmail:["Verify Email","","","","",""],
    didntrecievecode:["Didn't Recieve code","","","","",""],
    resend:["Resend","","","","",""],
    customerDashboard:["Customer Dashboard","","","","",""],
    cases:["Cases","","","","",""],
    dashboard:["Dashboard","","","","",""],
    applyCase:["Apply Case","","","","",""],
    caseStatus:["Case Status","","","","",""],
    caseSummary:["Case Summary","","","","",""],
    caseNumber:["Case Number","","","","",""],
    status:["Status","","","","",""],
}


export const windowServices = {
    windowService:["Window Services",""],
    login:["Login",""],
    username:["Username",""],
    password:["Password",""],
    forgotPassword:["Forgot Password",""],
    resetPassword:["Reset Password","",""],
    enteryourUsername:["Enter your username and password to continue",""],
    dashboard:["Dashboard",""],
    createCase:["Create Case",""],
    cases:["Cases",""],
    accountSettings:["Account Settings",""],
    logout:["Logout",""],
    Hello:["Hello",""],
    pending:["Pending",""],
    ongoing:["Ongoing",""],
    responded:["Responded",""],
    active:["Active",""],
    inactive:["Inactive",""],
    firstname:["First Name",""],
    middlename:["Middle Name",""],
    lastname:["Last Name",""],
    email:["Email",""],
    subCity:["Sub-city",""],
    woreda:["Woreda",""],
    gender:["Gender",""],
    male:["Male",""],
    female:["Female",""],
    phone:["Phone",""],
}

export const ethics = {
    companyName:["Addis Ababa Housing Development Corporation",""],
    ethicsManaement:["Ethics Management",""],
    toStayConnected:["To stay connected login back to your account with your credentials",""],
    login:["Login",""],
    logout:["Logout",""],
    username:["Username",""],
    password:["Password",""],
    confirmPassword:["Confirm Password",""],
    forgotPassword:["Forgot Password",""],
    resetPassword:["Reset Password",""],
    enteryourUsername:["Enter your username and password to continue",""],
    accusations:["Accusations",""],
    totalAccusations:["Total Accusations",""],
    accountSettings:["Account Settings",""],
    Hello:["Hello",""],
    active:["Active",""],
    inactive:["Inactive",""],
    subject:["Subject",""],
    accusedDeprtment:["Accused department",""],
    recievedOn:["Recieved On",""],
    personalInformation:["Personal Information",""],
    firstname:["First Name",""],
    middlename:["Middle Name",""],
    lastname:["Last Name",""],
    phone:["Phone",""],
    emailAddress:["Email Address",""],
    gender:["Gender",""],
    back:["Back",""],
    searchByname:["Search by name",""],
    searchByPhone:["Search by phone",""],
    latest:["Latest"],
    oldest:["Oldest",""],
    SomethingWentWrong:["Something went wrong",""],
    errorConnectingtoServer:["It seems like there was an error connecting to the server. Please try again later. Thank you for your patience.",""],
    reload:["Reload",""],
    pageNotFound:["Page Not Found",""],
    weCoudldNotFindThePage:["We couldn't find the page you are looking for.",""],
    passwordMatch:["Password and confirm password don't match",""]
    
}

export const archivalUsers = {
    archvial:["Archival",""],
    toStayConnected:["To stay connected login back to your account with your credentials",""],
    login:["Login",""],
    username:["Username",""],
    password:["Password",""],
    forgotPassword:["Forgot Password",""],
    resetPassword:["Reset Password",""],
    enteryourUsername:["Enter your username and password to continue",""],
    //letter
    internaLetter:["Internal Letter",""],
    externalLetter:["External Letter",""],
    createLetter:["Create Letter",""],
    letterType:["Letter type",""],
    letterNumber:["Letter Number",""],
    dateofSent:["Date of letter sent",""],
    sentfrom:["Sent from",""],
    sentTo:["Sent To",""],
    subject:["Subject",""],
    letterAttachment:["Letter Attachment",""],
    uploadLetter:["Upload Letter",""],
    cancel:["Cancel",""],
    from:["From",""],
    to:["To",""],
    remark:["Reamrk",""],
    createdBy:["Created By",""],
    archivedIn:["Archived In",""],
    createdDate:["Created Date",""],
    createdTime:["Created Time",""],
    cc:["Cc",""],
    letterContent:["Letter Content",""],
    stampedDate:["Stamped Date",""],
    stampedTime:["Stamped Time",""],
    stampedBy:["Stamped By",""],

    //case
    submittedDate:["Submited Date",""],
    division:["Division",""],
    caseNumber:["Case Number",""],
    status:["Status",""],
    relatedCaseNumber:["Related Case Number",""],
    customerName: ["Customer Name",""],
    caseRequest:["Case Request",""],
    attachement:["Attachement",""],
    scheduledDate:["Scheduled Date",""],
    scheduledTime:["Scheduled Time",""],
    extendedDate:["Extended Date",""],
    extendedTime:["Extended Time",""],
    scheduledBy:["Scheduled By",""],
    ongoingDate:["Ongoing Date",""],
    respondedDate:["Responded Date",""],
    verifiedDate:["Verified Date",""],
    rejectedDate:["Rejected Date",""],
    formFilledIn:["Form filled in",""],
    firstname:["First Name",""],
    middlename:["Middle Name",""],
    lastname:["Last Name",""],
    email:["Email",""],
    subCity:["Sub-city",""],
    woreda:["Woreda",""],
    gender:["Gender","",],
    phone:["Phone",""],
    male:["Male",""],
    female:["Female",""],
    late:["Late",""],
    responseJustification:["Response Justification",""],
    rejectionJustification:["Rejection Justification",""],
    stamp:["Stamp",""],

    //archival category
    archivalCategory:["Archival Category",""],
    createCategory:["Create Category",""],
    name:["Name",""],
    cateogryName:["Category Name",""],
    creatorName:["Creator Name",""],
    creatorusername:["Creator Username",""],
    cateogoryStatus:["Category Status",""],
    edit:["Edit",""],
    archivalCategoryName:["Archival Category Name",""],

}

export const it = {
    it:["IT",""],
    toStayConnected:["To stay connected login back to your account with your credentials",""],
    login:["Login",""],
    logout:["Logout",""],
    username:["Username",""],
    password:["Password",""],
    forgotPassword:["Forgot Password",""],
    enteryouremail:["Enter your email",""],
    getResetLink:["Get reset link",""],
    backToLogin:["Back to login",""],
    resetPassword:["Reset Password",""],
    enteryourUsername:["Enter your username and password to continue",""],
    hello:["Hello",""],
    companyName:["Addis Ababa Housing Development Corporation",""],
    dashboard:["Dashboard",""],
    accounts:["Accounts",""],
    orgStructure:["Org. Structure",""],
    caseList:["Case List",""],
    questions:["Questions",""],
    administrators:["Adminstrators",""],
    archivalUsers:["Archival Users",""],
    windowService:["Window Service",""],
    ethicsUsers:["Ethics Users",""],
    customers:["Customers",""],
    profile:["Profile",""],
    fullName:["Full Name",""],
    email:["Email",""],
    gender:["Gender",""],
    level:["Level",""],
    action:["Action",""],
    edit:["Edit",""],
    firstname:["First Name",""],
    middlename:["Middle Name",""],
    lastname:["Last Name",""],
    phoneNumber:["Phone Number",""],
    typeofPosition:["Type of Position",""],
    profilePicture:["Profile Picture",""],
    titer:["Titer",""],
    signiture:["Signiture",""],
    cancel:["Cancel",""],
    create:["Create",""],
    status:["Status",""],
    currentPicture:["Current Picture",""],
    createAdministrator:["Create Administrator",""],
    searchByUsername:["Search by username",""],
    searchByName:["Search by name",""],
    searchByEmail:["Search by email",""],
    searchByLevel:["Search by level",""],
    searchByStatus:["Search by status",""],
    searchByCaseList:["Search by case list",""],
    searchByDivisionName:["Search by division name",""],
    searchByDirectorateName:["Search by directorate name",""],
    searchByTeamName:["Search by team name",""],
    division:["Division",""],
    divisions:["Divisions",""],
    divisionNameEN:["Division name in english",""],
    divisionNameAM:["Division name in amharic",""],
    divisionNameOR:["Division name in oromo",""],
    divisionNameTI:["Division name in tigrgna",""],
    divisionNameAF:["Division name in afar",""],
    divisionNameSM:["Division name in somali",""],
    addnewDivision:["Add new division",""],
    directorate:["Directorate",""],
    directorates:["Directorates",""],
    addNewDirectorate:["Add new directorate",""],
    directoratenNameEN:["Directorate name in english",""],
    directorateNameAM:["Directorate name in amharic",""],
    directorateNameOR:["Directorate name in oromo",""],
    directorateNameTI:["Directorate name in tigrgna",""],
    directorateNameAF:["Directorate name in afar",""],
    directorateNameSM:["Directorate name in somali",""],
    addMembersToDirectorate:["Add Members to directorate",""],
    alreadyMembers:["Already Members",""],
    alreadyMembersToDirectorate:["Already members to directorate",""],
    removeFromDirectorate:["Remove from directorate",""],
    teams:["Teams",""],
    addNewTeam:["Add new team",""],
    addMembersToTeam:["Add members to team",""],
    paraph:["Paraph",""],
    addNewparaph:["Add new paraph",""],
    currentParaphs:["Current paraphs",""],
    adminInfo:["Administrator's Information",""],
    manager:["Manager",""],
    memebers:["Members",""],
    createdBy:["Created By",""],
    createdDate:["Created Date",""],
    createdTime:["Created Time",""],
    joinedIn:["Joined In",""],
    changeStatus:["Change Status",""],
    update:["Update",""],
    english:["English",""],
    amharic:["Amharic",""],
    tigrgna:["Tigrgna",""],
    oromo:["Oromo",""],
    afar:["Afar",""],
    somali:["Somali",""],
    timeLimit:["Time Limit",""],
    nameEN:["name in english",""],
    nameAM:["name in amharic",""],
    nameOR:["name in oromo",""],
    nameTI:["name in tigrgna",""],
    nameAF:["name in afar",""],
    nameSM:["name in somali",""],
    answeredBy:["Answered By",""],
    selectQuestions:["Select Questions",""],
    selectedQuestions:["Selected Questions",""],
    createAQuestion:["Create a question",""],
    editQuestion:["Edit Question",""],
    typeOfData:["Type of data",""],
    questionRequired:["Is this question required",""],
    typeOfInput:["Type of input",""],
    selectableValues:["Does this question have selectable values",""],
    yes:["Yes",""],
    no:["No",""],
    text:["Text",""],
    number:["Number",""],
    noOfSelectables:["How many selectables",""],
    expectedValue:["Expected value",""],
    PageNotFound:["Page not found",""],
    notFoundDescription:["We couldn't find the page you are looking for.",""],
    errorMessage:["Something went wrong",""],
    choice:["Choice",""],
    errorDescription:["It seems like there was an error connecting to the server. Please try again later. Thank you for your patience",""],
    caseRequests:["Case Requests",""],
    caseRequest:["Case Request",""],
    answerBy:["Answer By",""],
    timelimit:["Timelimit",""]


    
}

export const officeUsers={
    enteryourCred:["Enter your credentials to continue",""],
    login:["Login",""],
    logout:["Logout",""],
    username:["Username",""],
    password:["Password",""],
    forgotPassword:["Forgot Password",""],
    enteryouremail:["Enter your email",""],
    getResetLink:["Get reset link",""],
    backToLogin:["Back to login",""],
    resetPassword:["Reset Password",""],
    administrators:["Administrators",""],
    hello:["Hello",""],
    companyName:["Addis Ababa Housing Development Corporation",""],
    dashboard:["Dashboard",""],
    divisions:["Divisions",""],
    forwardCases:["Forward Cases",""],
    repliedCases:["Replied Cases",""],
    forwardedComplaints:["Forwarded Complaints",""],
    repliedComplaints:["Replied Complaints",""],
    forwardedLetters:["Forwarded Letters",""],
    repliedLetters:["Replied Letters",""],
    it:["IT",""],
    archivals:["Archivals",""],
    customers:["Customers",""],
    accountSettings:["Account Settings",""],
    totalCases:["Total Cases",""],
    totalComplaints:["Total Complaints",""],
    totalLetters:["Total Letters",""],
    internalMemo:["Internal Memeo",""],
    complaintSummary:["Complaint Summary",""],
    caseSummary:["Case Summary",""],
    divisionName:["Division Name",""],
    manager:["Manager",""],
    createdAt:["Created At",""],
    status:["Status",""],
    divisionInfo:["Division Information",""],
    email:["Email",""],
    phone:["Phone",""],
    gender:["Gender",""],
    division:["Division",""],
    level:["Level",""],
    position:["Position",""],
    titer:["Titer",""],
    signiture:["Signiture",""],
    canForward:["Can Forward",""],
    directorates:["Directorates",""],
    directorateName:["Directorate Name",""],
    directorateInfo:["Directorate Information",""],
    teams:["Teams",""],
    teamInformation:["Team Information",""],
    members:["Members",""],
    memberInformation:["Member Information",""],
    caseNumber:["Case Number",""],
    customerName:["Customer Name",""],
    responseDate:["Response Date",""],
    
}