export const language ={
    companyName:["Addis Ababa Housing Development Corporation","አዲስ አበባ ቤቶች ልማት ኮርፖሬሽን","","","",""],
    welcomeMessage:["Welcome To Addis Ababa Housing Development Corporation","እንኳን ወደ አዲስ አበባ በቶች ልማት ኮርፖሬሽን በደህና መጡ"],
    welcomeSubtitle:["Administrator's portal","የሃላፊዎች ፖርታል"],
    customer:["Customer","ደንበኛ","","","",""],
    checkStatus:["Check status","ሁኔታን ያረጋግጡ","","","",""],
    makeAccusation:["Make Accusation","ክስ ያቅርቡ","","","",""],
    name:["Name","ስም","","","",""],
    subject:["Subject","ርዕሰ ጉዳይ","","","",""],
    phone:["Phone","ስልክ","","","",""],
    description:["Description","መግለጫ","","","",""],
    attachement:["Attachment","አባሪ","","","",""],
    uploadAttachment:["Upload attachment","አባሪ ይጫኑ","","","",""],
    cancel:["Cancel","ሰርዝ","","","",""],
    submit:["Submit","አስገባ","","","",""],
    login:["Login","ግባ","","","",""],
    register:["Register","ይመዝገቡ","","",""],
    bannerTitle: ["Welcome To Addis Ababa Housing Development Corporation","እንኳን ወደ አዲስ አበባ ቤቶች ልማት ኮርፖሬሽን በደህና መጡ","","","",""],
    bannerSubTitle:["Customer Service","የደንበኞች አገልግሎት","","","",""],
    services:["Services","አገልግሎቶች","","","",""],
    division1:["Land Design and Infrastructure Development","የመሬት ዲዛይን እና የመሠረተ ልማት ግንባታ","","","",""],
    division2:["House Construction","የቤት ግንባታ","","",""],
    division3:["House Transfer and Construction Finance","የቤት ማስተላለፍ እና የግንባታ ፋይናንስ","","","",""],
    division4:["Corporate Service","የኮርፖሬት አገልግሎት","","","",""],
    managerNotAssigned:["This division does not have a manager assigned","ይህ ዘርፍ ሃላፊ አልተመደበለትም"],
    titernotUploaded:["Titer is not uploaded  for this user","ለዚ ተጠቃሚ ቲተር አልገባለትም"],
    signnotUploded:["Signiture is not uploaded  for this user","ለዚ ተጠቃሚ ፊርማ አልገባለትም"],
    noDirectorateFoundDivision:["No directorate found in this division","ይህ ዘርፍ ላይ ምንም አይነት ዳይሬክቶሬት አልተገኘም"],
    noteamFoundDirectorate:["No team found in this directorate","ይህ ዳይሬክቶሬት ውስጥ ምንም አይንት ቡድን አልተገኘም"],
    teamName:["Team Name","ቡድን ስም"],
    noTeamManagerFound:["Manager for this team is not found","ይህ ቡድን ሃላፉ አልተመደበልትም"],
    notmemberFoundTeam:["No member found in this team","ይህ ብድን አባል የሉትም"],
    searchByLateCases:["Search by late cases","የረፈዱ ጉዳዮች"],
    all:["All","ሁሉም"],
    forward:["Forward","ምራ"],
    reply:["Internal reply","የውስጥ ምላሽ ስጥ"],
    forwardPath:["Forward Path","የተመራበት መንገድ"],
    replyPath:["Reply Path","የተመለሰበት መንገድ"],
    schedule:["Schedule","ቀጠሮ ስጥ"],
    candidateResponse:["Candidate Response","ለደንበኛ እጩ ምላሽ አዘጋጅ"],
    reject:["Reject","ውድቅ አርግ"],
    respond:["Respond","ምላሽ ስጥ"],
    pendingDate:["Pending Date","መጠባብቅ ላይ የገባበት ቀን"],
    customerCaseAttachment:["Customer case request attachement","የደንበኛ ቅጽ ማብራሪያ አባሪ"],
    giveScheduleCase:["Give schedule to case","ለጉዳዩ ቀጠሮ ስጥ"],
    scheduleDate:["Schedule date","ቀጠሮ ቀን ስጥ"],
    rejectCase:["Reject case","ጉዳዮን ውድቅ አርግ"],
    candidateFileAttachment:["Candidate response file attachment","እጩ ምላሽ አባሪ"],
    extend:["extend","አራዝም"],
    youHaveNoForwarededCases:["You have no forwarded cases","ምንም የተመራ ጉዳይ የለም"],
    logintoyourAccount:["Login to your account","ወደ መለያዎ ይግቡ","","","",""],
    usernamePlaceholder:["Username","የተጠቃሚ ስም","","","",""],
    passwordPlaceholder:["password","የይለፍ ቃል","","","",""],
    forgotPasswordLink:["forgot your password","የሚስጥራዊውን ቁጥር ረስተዋል","","","",""],
    loginButton:["Sign In","ይግቡ","","","",""],
    createAnAccount:["Create An Account","መለያ ፍጠር","","","",""],
    firstname:["First Name","የመጀመሪያ ስም","","","",""],
    middlename:["Middle Name","የአባት ስም","","","",""],
    lastname:["Last Name","የአያት ስም","","","",""],
    preferredLanguage:["Preferred Language","የቋንቋ ምርጫ","","","",""],
    username:["Username","የተጠቃሚ ስም","","","",""],
    email:["Email","ኢሜይል","","","",""],
    subCity:["Sub-city","ክፍለ ከተማ","","","",""],
    woreda:["Woreda","ወረዳ","","","",""],
    houseNumber:["House Number","የቤት ቁጥር","","","",""],
    housePhoneNumber:["House Phone Number","የቤት ስልክ ቁጥር","","","",""],
    gender:["Gender","ጾታ","","","",""],
    selectGender:["Select Gender","ጾታ ይምረጡ","","","",""],
    male:["Male","ወንድ ","","","",""],
    female:["Female","ሴት","","","",""],
    password:["Password","የይለፍ ቃል","","","",""],
    confirmPassword:["Confirm Password","የይለፍ ቃል አረጋግጥ","","","",""],
    uploadProfileImage:["Upload Profile Image","የመገለጫ ምስል አስቀምጥ","","","",""],
    verifyYourEmail:["Verify your Email","ኢሜልዎን ያረጋግጡ","","","",""],
    weHaveSentACode:["We have sent a code to your email","ወደ ኢሜልዎ ኮድ ልከናል","","","",""],
    verifyEmail:["Verify Email","ኢሜል ያረጋግጡ","","","",""],
    didntrecievecode:["Didn't Recieve code","ኮድ አልተቀበለም","","","",""],
    resend:["Resend","እንደገና ላክ","","","",""],
    customerInformation:["Customer Information","የደንበኛ መረጃ","","","",""],
    print:["Print","አትም","","","",""],
    customerDashboard:["Customer Dashboard","የደንበኛ ዳሽቦርድ","","","",""],
    toManyRequests:["Too many attempts. Please try again later.","ተደጋጋሚ ሙከራ አድርገዋል። እባክዎ ትንሽ ኮይተው ይሞክሩ።","","","","",""],
    noAvailableCase:["No available cases","ምንም አይነት ጉዳይ አላመለከቱም","","","",""],
    cases:["Cases","ጉዳዮች","","","",""],
    dashboard:["Dashboard","ዳሽቦርድ","","","",""],
    applyCase:["Apply Case","ጉዳይ ማመልከቻ","","","",""],
    caseStatus:["Case Status","የጉዳይ ሁኔታ","","","",""],
    caseSummary:["Case Summary","የጉዳይ ማጠቃለያ","","","",""],
    caseNumber:["Case Number","የጉዳይ ቁጥር","","","",""],
    status:["Status","ሁኔታ","","","",""],
    windowService:["Window Services","የመስኮት አገልግሎቶች","","","",""],
    forgotPassword:["Forgot Password","የይለፍ ቁልፉን ረስተዋል","","","",""],
    resetPassword:["Reset Password","የይለፍ ቃል ይቀየሩ","","","","",""],
    enteryourUsername:["Enter your username and password to continue","ለመቀጠል የእርስዎን የመጠቀሚያ ስም እና የይለፍ ቃል ያስገቡ","","","",""],
    createCase:["Create Case","ጉዳይ ይክፈቱ","","","",""],
    accountSettings:["Account Settings","መለያ ማደራጃ","","","",""],
    logout:["Logout","ውጣ","","","",""],
    Hello:["Hello","ሰላም","","","","",""],
    pending:["Pending","በመጠባበቅ ላይ","","","",""],
    ongoing:["Ongoing","በመካሄድ ላይ","","","","",""],
    processing:["Processing","ፕሮሰሲኢንግ","","","",""],
    responded:["Responded","ተመልሷል","","","",""],
    verfied:["Verified","የተረጋገጠ","","","",""],
    rejected:["Rejected","ተቀባይነት አላገኘም","","","",""],
    caseInformation:["Case Information","የጉዳይ መረጃ","","","",""],
    recentCases:["Recent Cases","የቅርብ ጊዜ ጉዳዮች","","","",""],
    selectDivision:["Select Division","ዘርፍ ይምረጡ","","","",""],
    selectCaseRequest:["Select Case Request","ቅጽ ይምረጡ","","","",""],
    selectRelatedCaseNumber:["Select Related Case Number","ተዛማጅ የጉዳይ ቁጥር ይምረጡ","","","",""],
    apply:["Apply","ያመልክቱ","","","",""],
    noCases:["You have no cases","ምንም ዓይነት የገባ ጉዳይ የለም","","","",""],
    processingStartDate:["Processing Start Date","ፕሮሰስ መደረግ የጀመረበት ቀን","","","",""],
    scheduleInformation:["Schedule Information","የቀጠሮ መረጃ","","","",""],
    filledQuestions:["filled Questions","የተሞሉ ጥያቄዎች","","","",""],
    responseAttachment:["Response Attachment","ምላሽ አባሪ","","","",""],
    respondedBy:["Responded By","ምላሽ የሰጠው በ","","","",""],
    active:["Active","አክቲቭ","","","",""],
    inactive:["Inactive","ኢን-አክቲቭ","","","",""],
    ethicsManaement:["Ethics Management","የስነምግባር አስተዳደር","","","",""],
    toStayConnected:["To stay connected login back to your account with your credentials","ለመቀጠል የመጠቀሚያ ስም እና የይለፍ ቃል ያስገቡ","","","",""],
    accusations:["Accusations","ጥቆማ","","","",""],
    totalAccusations:["Total Accusations","ጠቅላላ ክሶች","","","",""],
    accusedDeprtment:["Accused department","የተከሰሰው ክፍል","","","",""],
    recievedOn:["Recieved On","ተቀብሏል","","",""],
    personalInformation:["Personal Information","የግል መረጃ","","","",""],
    emailAddress:["Email Address","የኢሜል አድራሻ","","","",""],
    back:["Back","ተመለስ","","","",""],
    retypePassword:["Re-type password","የይለፍ ቃል ድጋሜ ያስገቡ","","","","","",""],
    noDivision:["No division found","ምንም አይነት ዘርፍ የለም"],
    searchByname:["Search by name","በስም ፈልግ","","","",""],
    searchByPhone:["Search by phone","በስልክ ይፈልጉ","","","","",""],
    noArchvialFound:["No archival found","የመዝገብ ቤት ተጠቃሚ አልተገኘም"],
    archivalInformation:["Archival Information","የመዝገብ ቤት ተጠቃሚ መረጃ"],
    searchByCaseNumber:["Search by case number","በጉዳይ ቁጥር ይፈልጉ","","","",""],
    notification:["Notification","ኖቲፍክሽን"],
    read:["Read","የተነበበ"],
    unread:["Unread","ያልተነበበ"],
    lateCases:["Late cases","ያረፈዱ ጉዳዮች"],
    markasRead:["Mark as read","እንደተነበበ ምልክት አድርግበት"],
    view:["View","ተመልከት"],
    latest:["Latest","የቅርብ ጊዜ","","","",""],
    oldest:["Oldest","የቆየ","","","",""],
    rateService:["Are you statisfied with the service ?","በአገልግሎቱ ምን ያህል ረክተዋል","","","",""],
    SomethingWentWrong:["Something went wrong","የሆነ ስህተት ተከስቷል","","","",""],
    errorConnectingtoServer:["It seems like there was an error connecting to the server. Please try again later. Thank you for your patience."," ከአገልጋዩ ጋር መገናኘት ላይ ስህተት ያለ ይመስላል። እባክዎ ቆየት ብለው ይሞክሩ፤ ስለትግስትዎ አናመሰግናለን","","","",""],
    reload:["Reload","ዳግም ጫን","","","",""],
    pageNotFound:["Page Not Found","ገጹ አልተገኘም","","","",""],
    myProfile:["My Profile","የኔ ገጽታ","","","",""],
    weCoudldNotFindThePage:["We couldn't find the page you are looking for.","የሚፈልጉትን ገጽ ማግኘት አልቻልንም","","","",""],
    passwordMatch:["Password and confirm password don't match","የይለፍ ቃል እና የይለፍ ቃል ያረጋግጡ አይዛመዱም","","","",""],
    archvial:["Archival","መዝገብ ቤት","","","",""],
    internaLetter:["Internal Letter","የውስጥ ደብዳቤ","","","",""],
    internalLetters:["Internal Letters","የውስጥ ደብዳቤዎች"],
    externalLetter:["External Letter","የውጭ ደብዳቤ","","","",""],
    createLetter:["Create Letter","ደብዳቤ ይፍጠሩ","","","",""],
    letterType:["Letter type","የደብዳቤ አይነት","","","",""],
    letterNumber:["Letter Number","የደብዳቤ ቁጥር","","","",""],
    dateofSent:["Date of letter sent","የተላከ ደብዳቤ ቀን","","","",""],
    sentfrom:["Sent from","የተላከው ከ","","","",""],
    sentTo:["Sent To","የተላከው ለ","","","",""],
    letterAttachment:["Letter Attachment","ደብዳቤ አባሪ","","","",""],
    uploadLetter:["Upload Letter","ደብዳቤ ጫን","","","",""],
    from:["From","ከ","","","",""],
    caseAttachment:["Case Attachment","የጉዳይ አባሪ"],
    replyAttachment:["Reply Attachment","ምላሽ አባሪ"],
    to:["To","ለ","","","",""],
    remark:["Reamrk","ተጨማሪ ማብራሪያ","","","",""],
    createdBy:["Created By","የተመዘገበው በ","","","",""],
    archivedIn:["Archived In","ውስጥ ተመዝግቧል","","","",""],
    createdDate:["Created Date","የገባበት ቀን","","","",""],
    createdTime:["Created Time","የገባበት ጊዘ","","","",""],
    cc:["Cc","ግልባጭ","","","",""],
    letterContent:["Letter Content","የደብዳቤ ይዘት","","","",""],
    stampedDate:["Stamped Date","የታተመበት ቀን","","","",""],
    stampedTime:["Stamped Time","የታተመበት ሰዓት","","","",""],
    stampedBy:["Stamped By","ማህተም የተደረገው በ","","","",""],
    submittedDate:["Submited Date","የቀረበበት ቀን","","","",""],
    division:["Division","ዘርፍ","","","",""],
    forwardPathFor:["Forward path for","ጉዳዩ የተመራበት ሂደት"],
    forwardedDate:["Forwarded Date", "የተመራበት ቀን"],
    forwaededTime:["Forwarded Time","የተመራበት ሰዓት"],
    forwardedInformation:["Forward Information","የተመራበት መረጃ"],
    replyPathFor:["Reply Path for","የተመለሰበት መንገድ ለ"],
    repliedDate:["Replied Date","የተመለሰበት ቀን"],
    repliedTime:["Replied Time","የተመለሰበት ሰዓት"],
    relatedCaseNumber:["Related Case Number","ተዛማጅ የጉዳይ ቁጥር","","","",""],
    customerName: ["Customer Name","የደንበኛ ስም","","","",""],
    caseRequest:["Case Request","የጉዳይ ጥያቄ (ቅጽ)","","","",""],
    percentage:["percentage","መቶኛ"],
    onlineCustomers:["Online Customers","መለያ ያላቸው ደንበኞች"],
    windowServiceCustomers:["Window service customers","በአንድ መስኮት የተገለገሉ ደንበኞች"],
    weeklyCases:["Weekly Cases","በዚ ሳምንት የገቡ ጉዳዮች"],
    noCasesWeek:["No available cases for this week","በዚ ሳምንት የገባ ጉዳይ የለም"],
    divisionRating:["Division Rating","የዘርፎች ሬቲንግ"],
    ratings:["Ratings","ሬቲንግ"],
    noRatings:["No Available ratings","ሬት የተደረገ ዘርፍ የለም"],
    noCaseDivisionWeek:["There are no cases for this division this week","በዚህ ሳምንት ለዚህ ዘርፍ ምንም የገባ ጉዳዮች የሉም"],
    noParaph:["Empty paraph list","ምንም አይነት ፓራፍ አልተጨመረም"],
    paraphTitle:["Paraph Title","የፓራፍ ርዕስ"],
    scheduledDate:["Scheduled Date","የቀጠሮ ቀን","","","",""],
    scheduledTime:["Scheduled Time","የቀጠሮ ሰዓት","","","",""],
    extendedDate:["Extended Date","የተራዘመ ቀን","","","",""],
    extendedTime:["Extended Time","የተራዘመ ሰዓት","","","",""],
    extendedBy:["Extended By","የተራዘመው በ","","","",""],
    scheduledBy:["Scheduled By","ቀጠሮ የተያዘለት በ ","","","",""],
    ongoingDate:["Ongoing Date","ወደ ስራ የገባበት  ቀን","","","",""],
    respondedDate:["Responded Date","ምላሽ የተሰጠበት ቀን","","","",""],
    verifiedDate:["Verified Date","የተረጋገጠ ቀን","","","",""],
    verfiedBy:["Verified By","የተረጋገጠው በ","","","",""],
    finalFileAttachment:["Final file attachment","የመጨረሻ አባሪ","","","",""],
    rejectedDate:["Rejected Date","ውድቅ የተደረገበት ቀን","","","",""],
    reasonOfRejection:["Reason of Rejection","ውድቅ የተደረገበት ምክንያት","","","",""],
    fromReply:["From reply","ከምላሽ ውስጥ"],
    fromUpload:["From upload","ከአባሪ"],
    noReplyFOund:["No reply found","ምላሽ አልተገኘም"],
    formFilledIn:["Form filled in","ቅጽ ተሞልቷል","","","",""],
    late:["Late","ረፍዷል","","","",""],
    responseJustification:["Response Justification","ምላሽ ጽድቅ","","","",""],
    rejectionJustification:["Rejection Justification","ውድቅ የተደረገበት ምክንያት","","","",""],
    candidateResponseCase:["Candidate response for case","እጩ ምላሽ ለጉዳይ"],
    noccCases:["You have no cc cases","ምንም የገባ ግልባጭ ጉዳይ የለም"],
    createIT:["Create IT user","አይቲ ተጠቃሚ ይፍጠሩ"],
    itNotFound:["No IT user found","ምንም አይንት አይቲ ተጠቃሚ አልተገኘም"],
    edit:["Edit","ለማስተካከል"],
    updatedBy:["Updated by","የተስተካከለው በ"],
    detach:["Detach","ዲታች"],
    save:["Save","ሴቭ"],
    preview:["Preview","ቅድመ እይታ"],
    created:["Created By","የመጀመሪያ መላሽ"],
    createdl:["Created","ተመዝግቧል"],
    forwardedl:["Forwarded","ተመርቷል"],
    response:["Response","ምላሽ ያስቀምጡ"],
    attachementType:["Attachment type","የባሪ አይነት"],
    stamp:["Stamp","አትም","","","",""],
    archivalCategory:["Archival Category","የማህደር ምድብ","","","",""],
    createCategory:["Create Category","ምድብ ፍጠር","","","",""],
    cateogryName:["Category Name","የምድብ ስም","","","","",""],
    creatorName:["Creator Name","የፈጣሪ ስም","","","",""],
    creatorusername:["Creator Username","የፈጣሪ የተጠቃሚ ስም","","","",""],
    cateogoryStatus:["Category Status","የምድብ ሁኔታ","","","",""],
    browse:["Choose picture","ፎቶ ይምረጡ"],
    editIT:["Edit IT Information","የኢይቲ መረጃ ያስተካክሉ"],
    itInformation:["IT Information","አይቲ መረጃ"],
    norepliedcases:["You have no replied cases","የተመለሰ ጉዳይ የለም"],
    noCasesFound:["No cases found","ምንም የገባ ጉዳይ የለም"],
    archivalCategoryName:["Archival Category Name","የማህደር ምድብ ስም","","","",""],
    it:["IT","አይቲ","","","","",""],
    enteryouremail:["Enter your email","የእርስዎን ኢሜይል ያስገቡ","","","",""],
    getResetLink:["Get reset link","የይለፍ ቃል መቀየሪያ መስፈንጠሪያ ያግኙ","","","",""],
    backToLogin:["Back to login","ወደ መግቢያ ተመለስ"],
    hello:["Hello","ሀሎ "],
    selam:["Selam","ሰላም"],
    accounts:["Accounts","መለያ"],
    orgStructure:["Org. Structure","ኦርግ መዋቅር"],
    caseList:["Case List","የጉዳይ ዝርዝር"],
    questions:["Questions","ጥያቄዎች"],
    administrators:["Administrators","አስተዳዳሪዎች"],
    ccCases:["Cc Cases","ግልባጭ ጉዳዮች"],
    archivalUsers:["Archival Users","የማህደር ተጠቃሚዎች"],
    ethicsUsers:["Ethics Users","የስነምግባር ተጠቃሚዎች"],
    customers:["Customers","ደንበኞች"],
    profile:["Profile","መገለጫ"],
    fullName:["Full Name","ሙሉ ስም"],
    level:["Level","ደረጃ"],
    action:["Action","ድርጊት"],
    phoneNumber:["Phone Number","ስልክ ቁጥር"],
    typeofPosition:["Type of Position","የስራ ክፍል"],
    profilePicture:["Profile Picture","የመገለጫ ሥዕል"],
    titer:["Titer","ቲተር"],
    signiture:["Signiture","ፊርማ"],
    create:["Create","ፍጠር"],
    currentPicture:["Current Picture","የአሁኑ ሥዕል"],
    createAdministrator:["Create Administrator","አስተዳዳሪ ፍጠር"],
    searchByCustomerName:["Search by customer name","በደንበኛ ስም ይፈልጉ"],
    searchByUsername:["Search by username","በተጠቃሚ ስም ፈልግ"],
    searchByName:["Search by name","በስም ፈልግ"],
    searchByEmail:["Search by email","በኢሜል ይፈልጉ"],
    searchByLevel:["Search by level","በደረጃ ይፈልጉ"],
    searchByStatus:["Search by status","በሁኔታ ይፈልጉ"],
    searchByCaseList:["Search by case list","በጉዳይ ዝርዝር ይፈልጉ"],
    searchByDivisionName:["Search by division name","በዘርፍ ስም ይፈልጉ"],
    searchByDirectorateName:["Search by directorate name","በዳይሬክቶሬት ስም ይፈልጉ"],
    noCustomerFound:["No customer found","ምንም ዓይነት ደንበኛ አልተገኘም"],
    picture:["Picture","ፎቶ"],
    ethicsUserInformation:["Ethics user information","የስነምግባር ተጠቃሚ መረጃ"],
    noWindowServiceFound:["No window service found","ምንም የአንድ መስኮት ተጠቃሚ አልተገኘም"],
    windowServiceInformation:["Window service information","የአንድ መስኮት አገልግሎት ተጠቃሚ መረጃ"],
    searchByTeamName:["Search by team name","በቡድን ስም ይፈልጉ"],
    divisions:["Divisions","ዘርፎች"],
    divisionNameEN:["Division name in english","የዘርፍ ስም በእንግሊዝኛ"],
    divisionNameAM:["Division name in amharic","የዘርፍ ስም በአማርኛ"],
    divisionNameOR:["Division name in oromo","የዘርፍ ስም በኦሮምኛ"],
    divisionNameTI:["Division name in tigrgna","የዘርፍ ስም በትግርኛ"],
    divisionNameAF:["Division name in afar","የዘርፍ ስም በአፋርኛ"],
    divisionNameSM:["Division name in somali","የዘርፍ ስም በሶማልኛ"],
    addnewDivision:["Add new division","አዲስ ዘርፍ ጨምር"],
    directorate:["Directorate","ዳይሬክቶሬት"],
    directorates:["Directorates","ዳይሬክቶሬቶች"],
    addNewDirectorate:["Add new directorate","አዲስ ዳይሬክቶሬት ያክሉ"],
    directoratenNameEN:["Directorate name in english","የዳይሬክቶሬት  ስም በእንግሊዝኛ"],
    directorateNameAM:["Directorate name in amharic","የዳይሬክቶሬት ስም በአማርኛ "],
    directorateNameOR:["Directorate name in oromo","የዳይሬክቶሬት ስም በኦሮምኛ"],
    directorateNameTI:["Directorate name in tigrgna","የዳይሬክቶሬት ስም በትግርኛ"],
    directorateNameAF:["Directorate name in afar","የዳይሬክቶሬት ስም በአፋርኛ"],
    directorateNameSM:["Directorate name in somali","የዳይሬክቶሬት ስም በሶማልኛ"],
    addMembersToDirectorate:["Add Members to directorate","አባላትን ወደ ዳይሬክቶሬት ያክሉ"],
    alreadyMembers:["Already Members","ቀድሞውኑ አባላት"],
    alreadyMembersToDirectorate:["Already members to directorate","ቀድሞውኑ አባላት ወደ ዳይሬክቶሬት"],
    removeFromDirectorate:["Remove from directorate","ከዳይሬክቶሬት አስወጣ"],
    teams:["Teams","ቡድኖች"],
    addNewTeam:["Add new team","አዲስ ቡድን ያክሉ"],
    addMembersToTeam:["Add members to team","አባላትን ወደ ቡድን ያክሉ"],
    paraph:["Paraph","ፓራፍ"],
    addNewparaph:["Add new paraph","አዲስ ፓራፍ ጨምር"],
    currentParaphs:["Current paraphs","አሁን ያላት ፓራፍ"],
    adminInfo:["Administrator's Information","የአስተዳዳሪ መረጃ"],
    manager:["Manager","ሃላፊ"],
    memebers:["Members","አባላት"],
    joinedIn:["Joined In","ተቀላቅሏል"],
    changeStatus:["Change Status","ሁኔታን ቀይር"],
    update:["Update","አዘምን"],
    english:["English","እንግሊዝኛ"],
    amharic:["Amharic","አማርኛ"],
    tigrgna:["Tigrgna","ትግርኛ"],
    oromo:["Oromo","ኦሮምኛ"],
    afar:["Afar","አፋርኛ"],
    somali:["Somali","ሶማሊኛ"],
    timeLimit:["Time Limit","የጊዜ ገደብ"],
    nameEN:["name in english","ስም በእንግሊዝኛ"],
    nameAM:["name in amharic","ስም በአማርኛ"],
    nameOR:["name in oromo","ስም በኦሮምኛ"],
    nameTI:["name in tigrgna","ስም በትግርኛ"],
    nameAF:["name in afar","ስም በአፋርኛ"],
    nameSM:["name in somali","ስም በሶማልኛ"],
    answeredBy:["Answered By","መልስ በ"],
    selectQuestions:["Select Questions","ጥያቄዎችን ይምረጡ"],
    selectedQuestions:["Selected Questions","የተመረጡ ጥያቄዎች"],
    createAQuestion:["Create a question","ጥያቄ ፍጠር"],
    editQuestion:["Edit Question","ጥያቄን ያርትዑ"],
    typeOfData:["Type of data","የመረጃ አይነት"],
    questionRequired:["Is this question required","ይህ ጥያቄ ያስፈልጋል"],
    typeOfInput:["Type of input","የማስገቢያ አይነት"],
    selectableValues:["Does this question have selectable values","ይህ ጥያቄ ሊመረጡ የሚችሉ እሴቶች አሉት?"],
    yes:["Yes","አዎ"],
    no:["No","አይ"],
    text:["Text","ጽሑፍ"],
    number:["Number","ቁጥር"],
    noOfSelectables:["How many selectables","ምን ያህል ሊመረጡ የሚችሉ"],
    expectedValue:["Expected value","የሚጠበቀው ዋጋ"],
    PageNotFound:["Page not found","ገጹ አልተገኘም"],
    notFoundDescription:["We couldn't find the page you are looking for.","የሚፈልጉትን ገጽ ማግኘት አልቻልንም።"],
    errorMessage:["Something went wrong","የሆነ ስህተት ተከስቷል"],
    choice:["Choice","ምርጫ"],
    errorDescription:["It seems like there was an error connecting to the server. Please try again later. Thank you for your patience","ከአገልጋዩ ጋር መገናኘት ላይ ስህተት ያለ ይመስላል። እባክዎ ቆየት ብለው ይሞክሩ::ስለትግስትዎ አናመሰግናለን"],
    caseRequests:["Case Requests","የጉዳይ ዝርዝሮች"],
    answerBy:["Answer By","መልስ በ"],
    timelimit:["Timelimit","የጊዜ ገደብ"],
    enteryourCred:["Enter your credentials to continue","ለመቀጠል የመጠቀሚያ ስም አና የይለፍ ቃል  ያስገቡ"],
    forwardCases:["Forward Cases","የተመሩ ጉዳዮች"],
    repliedCases:["Replied Cases","የተመለሱ ጉዳዮች"],
    forwardedComplaints:["Forwarded Complaints","የተመሩ ቅሬታዎች"],
    repliedComplaints:["Replied Complaints","የተመለሱ ቅሬታዎች"],
    forwardedLetters:["Forwarded Letters","የተመሩ ደብዳቤዎች "],
    repliedLetters:["Replied Letters","የተመለሱ ደብዳቤዎች"],
    archivals:["Archivals","መዝገብ ቤት ተጠቃሚዎች"],
    verifyCases:["Verify cases","ጉዳይ ማረጋገጫ","","","",""],
    totalCases:["Total Cases","ጠቅላላ ጉዳዮች","","","",""],
    pendingCases:["Pending Cases","አዲስ የገባ ጉዳዮች","","","",""],
    processingCases:["Processing Cases","በሂደት ላይ ያሉ ጉዳዮች","","","",""],
    respondedCases:["Responded Cases","የተመለሱ ጉዳዮች","","","",""],
    rejectedCases:["Rejected Cases","ውድቅ የተደረጉ ጉዳዮች","","","",""],
    totalComplaints:["Total Complaints","ጠቅላላ ቅሬታዎች"],
    totalLetters:["Total Letters","ጠቅላላ ደብዳቤዎች"],
    internalMemo:["Internal Memo","ውስጣዊ ማስታወሻ"],
    totalOnlineCustomers:["Total Online Customers","መለያ የከፈቱ ደንበኞች"],
    administratorsLevel:["Administrators","የሃላፊዎች ደረጃ"],
    administratorsGender:["Administrators Gender","የሃላፊዎች ጾታ"],
    administratorsStatus:["Administrators Status","የሃላፊዎች ሁኔታ"],
    mainExecutive:["Main Executive","ዋና ዳይሬክትር"],
    divisionManagers:["Division Managers","የዘርፍ ሃላፊ"],
    director:["Director","ዳይሬክትር"],
    teamleaders:["Team Leader","የቡድን መሪ"],
    professsionals:["Professionals","ባለሞያ"],
    frequentlyFilledCaseRequest:["Frequently filled case requests","በተደጋጋሚ የተሞሉ ቅጾች"],
    nofilledCaseRequest:["There is no filled case request this week.","በዚ ሳምንት የተሞላ ቅጽ የለም"],
    customerAnalysis:["Customer Analysis","የደንበኛ ትንተና"],
    complaintSummary:["Complaint Summary","የቅሬታ ማጠቃለያ"],
    totalLateCases:["Total Late Cases","ጠቅላላ የዘገዩ ጉዳዮች"],
    currentLateCases:["Current Late Cases","የዘገዩ ጉዳዮች"],
    divisionName:["Division Name","የዘርፍ ስም"],
    createdAt:["Created At","የተፈጠረው ቀን"],
    divisionInfo:["Division Information","የዘርፍ መረጃ"],
    position:["Position","ክፍል"],
    canForward:["Can Forward","ለማ መምራት"],
    directorateName:["Directorate Name","የዳይሬክቶሬት ስም"],
    directorateInfo:["Directorate Information","የዳይሬክቶሬት መረጃ"],
    teamInformation:["Team Information","የቡድን መረጃ"],
    members:["Members","አባላት"],
    memberInformation:["Member Information","የአባል መረጃ"],
    responseDate:["Response Date","የተመለበት ቀን"],
    customerResponse:["Respond to customer","ለደንበኛ ምላሽ ስጥ"],
    letterInformation:["Letter Information","የደብዳቤው መረጃ"],
    ccLetters:["Cc Cases","ግልባጭ ደብዳቤዎች"],
    weeklyIncomingLetters:["Weekly incoming letters","በዚ ሳምንት ገቢ የተደረጉ ደብዳቤዎች"],
    weeklyOutgoingLetters:["Weekly outgoing letters","በዚ ሳምንት ወጪ የተደረጉ ደብዳቤዎች"],
    weeklyRespondedCases:["Weekly responded cases","በዚ ሳምንት ለማረጋገጫ የመጡ ጉዳዮች"],
    weeklyVerifiedCases:["Weekly verfied cases","በዚ ሳምንት ማረጋገጫ የተሰጣጨው ጉዳዮች"],
    weeklyForwardedLetters:["Weekly forwarded Letters","በዚ ሳምንት የተመሩ ደብዳቤዎች"],
    weeklyInternalLetters:["Weekly internal letters","በዚ ሳምንት የውስጥ ደብድቤዎች"],
    incomingLetters:["Incoming Letters","ገቢ ደብዳቤዎች"],
    outgoingLetters:["Outgoing Letters","ወጪ ደብዳቤዎች"],
    searchByLetterNumber:["Search by letter number (NIMMERA)","በደብዳቤ ቁጥር (ንምራ) ይፈልጉ"],
    letterSent:["Date of delivery","የተላከበት ቀን"],
    letterReceived:["The date the letter was received","የገባበት ቀን"],
    candidateLetter:["Candidate Letter","እጩ ደብዳቤ"],
    prepareCandidateLetter:["Prepare Candidate Letter","እጩ ደብዳቤ አዘጋጅ"],
    body:["Body","ሃተታ"],
    internalCc:["Internal Cc","የውስጥ ግልባጭ"],
    externalCc:["External Cc","ግልባጭ"],
    noOfExternalCC:["No. of external cc","በውጪ ግልባጭ የሚደርሳቸው ብዛት"],
    forwardedMemo:["Forwarded memo","የተመሩ ማስታወሻዎች"],
    ccMemo:["Cc memo","ግልባጭ ማስታወሻዎች"],
    repliedMemo:["Replied memo","የተመለሱ ማስታወሻዎች"],
    noOftos:["to (quantity)","ለ (ብዛት)"],
    incoming:["Incoming","ገቢ"],
    outgoing:["Outgoing","ወጪ"],
    internal:["Internal","የውስጥ"],
    presystem:["Presystem","ከሲስተም በፊት"],
    searchByFrom:["Search by sender name","በላኪ ስም ይፈልጉ"],
    noforwardedLetter:["No forwarded letters","ምንም የተመራ ደብዳቤ የለም"],
    noccLetter:["No forwarded letters","ምንም ግልባጭ ደብዳቤ የለም"],
    norepliedLetter:["No replied letters","ምንም የተመለሰ ደብዳቤ የለም"],
    letter:["Letter","ደብዳቤው","","","",""],
    archivalUser:["Archival User","የመዝገብ ቤት ተጠቃሚ"], 
    noForwardPathCase:["No forward path available","ይህ ጉዳይ አልተመራም"],
    noReplyPathCase:["No forward path available","ይህ ጉዳይ አልተመለሰም"],
    noForwardPathLetter:["No forward path available","ይህ ደብዳቤ አልተመራም"],
    noReplyPathLetter:["No reply path available","ይህ ደብዳቤ አልተመለሰም"],
    forwardedTime:["Forwarded Time","የተመራበት ሰዓት"],
    forwardedPathIncoming:["Forwarded path for incoming letter number","የተመራበት መንገድ ለገቢ ደብዳቤ"],
    forwardedPathOutgoing:["Forwarded path for outgoing letter number","የተመራበት መንገድ ለወጪ ደብዳቤ"],
    forwardedPathInternal:["Forwarded path for internal letter number","የተመራበት መንገድ ለውስጥ ደብዳቤ"],
    forwardedPathPresystem:["Forwarded path for presystem letter number","የተመራበት መንገድ  ለደብዳቤ (የበፊት)"],
    forwardedPatMemo:["Forwarded path for internal memo","የተመራበት መንገድ  ለውስጥ ማስታወሻ"],
    forwardPathDetailIncoming:["Forward path information for incoming letter","የተመራበት መንገድ መረጃ ለገቢ ደብዳቤ"],
    forwardPathDetailOutgoing:["Forward path information for outgoing letter","የተመራበት መንገድ መረጃ ለወጪ ደብዳቤ"],
    forwardPathDetailInternal:["Forward path information for internal letter","የተመራበት መንገድ መረጃ ለውስጥ ደብዳቤ"],
    forwardPathDetailPresystem:["Forward path information for presystem letter","የተመራበት መንገድ መረጃ ለደብዳቤ (የበፊት)"],
    forwardPathDetailMemo:["Forward path information for internal memo","የተመራበት መንገድ መረጃ ለውስጥ ማስታወሻ"],
    replyPathIncoming:["Reply path for incoming letter number","የተመለሰበት መንገድ ለገቢ ደብዳቤ"],
    replyPathOutgoing:["Reply path for outgoing letter number","የተመለሰበት መንገድ ለወጪ ደብዳቤ"],
    replyPathInternal:["Reply path for internal letter number","የተመለሰበት መንገድ ለውስጥ ደብዳቤ"],
    replyPathPresystem:["Reply path for presystem letter number","የተመለሰበት መንገድ  ለደብዳቤ ለደብዳቤ (የበፊት)"],
    replyPathMemo:["Reply path for internal memo","የተመለሰበት መንገድ ለውስጥ ማስታወሻ"],
    replyPathDetailIncoming:["Reply path information for incoming letter","የተመለሰበት መንገድ መረጃ ለገቢ ደብዳቤ"],
    replyPathDetailOutgoing:["Reply path information for outgoing letter","የተመለሰበት መንገድ መረጃ ለወጪ ደብዳቤ"],
    replyPathDetailInternal:["Reply path information for internal letter","የተመለሰበት መንገድ መረጃ ለውስጥ ደብዳቤ"],
    replyPathDetailPresystem:["Reply path information for presystem letter","የተመለሰበት መንገድ መረጃ ለደብዳቤ (የበፊት)"],
    replyPathDetailMemo:["Reply path information for internal memo","የተመለሰበት መንገድ መረጃ ለውስጥ ማስታወሻ"],
    incomingLetter:["Incoming Letter","ገቢ ደብዳቤ"],
    outgoingLetter:["Outgoing Letter","ወጪ ደብዳቤ"],
    internalLetter:["Internal Letter","የውስጥ ደብዳቤ"],
    presystemLetter:["Presystem Letter","ለደብዳቤ (ከሲስተም በፊት)"],
    forwardCc:["Forward Cc","የተመሩ ግልባጮች"],
    replyCc:["Reply Cc","የምላሽ ግልባጮች"],
    noNotifcationFound:["No notification found","ምንም አይነት ኖቲፊኬሽን አልተገኘም"],
    lateIncomingLetters:["Late incoming letters","ያረፈዱ ገቢ ደብዳቤዎች"],
    lateOutgoingLetters:["Late outgoing letters","ያረፈዱ ወጪ ደብዳቤዎች"],
    lateInternalLetters:["Late internal letters","ያረፈዱ የውስጥ ደብዳቤዎች"],
    letterAnalysis:["Letter analysis","የደብዳቤዎች ትንተና"],
    yearlyLetterAnalysis:["Yearly letter analysis","ዓመታዊ የገቢ ደብዳቤ ትንተና"],
    yearlyOutgoingLetterAnalysis:["Yearly outgoing letter analysis","ዓመታዊ የወጪ ደብዳቤ ትንተና"],
    yearlyInternalLetterAnalysis:["Yearly internal letter analysis","ዓመታዊ የውስጥ ደብዳቤ ትንተና"],
    monthlyIncomingLetterAnalysis:["Monthly letter analysis","ወርሃዊ የገቢ ደብዳቤ ትንተና"],
    monthlyOutgoingLetterAnalysis:["Monthly outgoing letter analysis","ወርሃዊ የወጪ ደብዳቤ ትንተና"],
    monthlyInternalLetterAnalysis:["Monthly internal letter analysis","ወርሃዊ የውስጥ ደብዳቤ ትንተና"],
    monthlyCaseAnalysis:["Monthly case analysis","ወርሃዊ የጉዳይ ትንተና"],
    verifiedCases:["Verified Cases","የተረጋገጡ ጉዳዮች"],
    caseAnalysis:["Case Analysis","የጉዳይ ትንተና"],
    special:["Called by main director","በዋና ዳይሬክተር ተጠሪ"],
    createOutgoingLetter:["Create outgoing letter","ወጪ ደብዳቤ ፍጠር"],
    createdLetters:["Created Letters","የተፈጠሩ ደብዳቤዎች"],
    nocreatedLetters:["You haven't created any letters yet","ምንም ደብዳቤ አልተገኝም"],
    createInternalLetter:["Create internal letter","የውስጥ ደብዳቤ ፍጠር"],
    approve:["Approve","አጽድቅ"],
    approvedBy:["Approved by","የሚጸድቀው በ"],
    approved:["approved","ጸድቋል"],
    approvedDate:["Approved date","የጸደቀበት ቀን"],
    searchByLetterNumbers:["Search by letter number","በደብዳቤ ቁጥር  ይፈልጉ"],
    organizationname:["Organization  name","የተቋም ስም"],
    location:["Location","አድራሻ"],
    add:["Add","ጨምር"],
    remove:["Remove","አስወግድ"],
    mainLetter:["Main Letter","ዋና ደብዳቤ"],
    caseNotUpdated:["This case hasn't been updated","ይህ ጉዳይ መስተካከያ አልተደረገለትም"],
    letterNotUpdated:["This letter hasn't been updated.","ይህ ደብዳቤ መስተካከያ አልተደረገለትም"],
    updatecaseList:["List of corrections to this case response","ይህ የእጩ ጉዳይ ላይ ማስተካከያ ያረጉ ሃላፉ/ባለሞያ ዝርዝር"],
    updateList:["List of corrections to this letter / memo","ይህ ደብዳቤ /  ላይ ማስተካከያ ያረጉ ሃላፉ/ባለሞያ ዝርዝር"],
    modifyLetter:["Modify Letter","ደብዳቤውን አስተካክል"],
    noIncomingLetterWeek:["No incoming letter this week","በዚ ሳመንት ምንም ገቢ ደብዳቤ አልተመዘገበም"],
    noOutgoingLetterWeek:["No outgoing letter this week","በዚ ሳመንት ምንም ወጪ ደብዳቤ አልተመዘገበም"],
    noInternalLetterWeek:["No outgoing letter this week","በዚ ሳመንት ምንም የውስጥ ደብዳቤ አልተመዘገበም"],
    letterTypeOption:["Please specify the type of letter, it must be incoming, outgoing internal or presystem.","እባክዎ የደብዳቤውን አይነት ይግለጹ፣ ገቢ፣ ወጪ ወይም ውስጣዊ መሆን አለበት።"],
    updatedDate:["Updated date","የተስተካከለበት ቀን"],
    updatedTime:["Updated time","የተስተካከለበት ሰዐት"],
    cutoffLetters:["Presystem  Letters","ከሲስተም በፊት የነበሩ ደብዳቤዎች"],
    searchByNIMMERA:["Search by letter number (NIMMERA)","በደብዳቤ ቁጥር (ንምራ) ይፈልጉ"],
    forwarded:["Forwarded","ተመርቷል"],
    noIncomingLetter:["No incoming letter found","ምንም ገቢ ደብዳቤ አልተገኘም"],
    noOutgoingLetter:["No outgoing letter found","ምንም ውጪ ደብዳቤ አልተገኘም"],
    noInternalLetter:["No internal letter found","ምንም የውስጥ ደብዳቤ አልተገኘም"],
    noPresystemLetter:["No presystem letter found","ምንም  ደብዳቤ አልተገኘም"],
    noInternalMemo:["No internal memo  found","ምንም  የወስጥ ማስታወሻ አልተገኘም"],
    archivalNumber:["Archival Number","መዝገብ ቁጥር"],
    totalIncomingLetters:["Total incoming letters","አጠቃላይ ገቢ ደብዳቤዎች"],
    totalOutgoingLetters:["Total outgoing letters","አጠቃላይ ወጪ ደብዳቤዎች"],
    totalInternalLetters:["Total internal letters","አጠቃላይ የውስጥ ደብዳቤዎች"],
    totalPresystemLetters:["Total presystem letters","አጠቃላይ ከሲስተም በፊት የነበሩ ደብዳቤዎች"],
    noLetter:["No letter found","ደብዳቤው አልተገኘም"],
    noOfAttachment:["Number of attachment","የአባሪ ብዛት"],
    createMemo:["Create internal memmo","የውስጥ ማስታወሻ ፍጠር"],
    createdMemo:["Created memos","የተፈጠሩ የወስጥ ማስታወሻ"],
    modifyMemo:["Modify memo","ማስተወሻውን አስተካክል"],
    noForwardedMemo:["No forwarded memo","ይተመራ የውስጥ ማስታወሻ አልተገኘም"],
    noRepliedMemo:["No replied memo","የተመለሰ ማስታወሻ አልትገኘም"],
    forwardedInternalMemo:["Forwarded memo","የተመሩ ማስታወሻዎች"],
    noccMemo:["No Cc memo","ምንም ግልባጭ ማስታወሻ የለም"],
    totalLateIncomingLetters:["Total Late incoming letters","አጠቃላይ የዘገዩ ገቢ ደብዳቤዎች"],
    currentLateIncomingLetters:["Current late incoming letters","የዘገዩ ገቢ ደብዳቤዎች"],
    totalLateOutgoingLetters:["Total late outgoing letters","አጠቃላይ የዘገዩ ውጪ ደብዳቤዎች"],
    currentLateOutgoingLetters:["Current late outgoing letters","የዘገዩ ውጪ ደብዳቤዎች"],
    totalLateInternalLetters:["Total late internal letters","አጠቃላይ የዘገዩ ይውስጥ ደብዳቤዎች"],
    currentLateInternalLetters:["Current late internal letters","የዘገዩ የውስጥ ደብዳቤዎች"],
    createdIncomingLetters:["created incoming letters","መዝግበው ያስገቡት ገቢ ደብዳቤ"],
    verifiedInternalLetters:["Verified internal letter","የተረጋገጠ የውስጥ ደብዳቤ"],
    verifiedOutgoingLetters:["Verified internal letter","የተረጋገጠ ውጪ ደብዳቤ"],
    currentDateCases:["Case created today","ዛሬ ያስተናገዱት የጉዳይ ብዛት"],
    totalInternalMemo:["Total Internal Memo","አጠቀላይ የውስጥ ማስታወሻዎች"],
    extendDate:["Extend Date","ቀጠሮውን አራዝም"],
    teamLeader:["Team Leader","ቡድን መሪ"],
    scheduleList:["Appointment List","የቀጠሮ ዝርዝር"],
    searchByScheduleDate:["Search by schedule date","በቀጠሮ ቀን ፈልግ"],
    extended:["Extended","ተራዝሟል"],
    noSchedule:["You have no customer appointments for this day","ለዚህ ቀን ምንም የደንበኛ ቀጠሮ የለዎትም።"],
    appointmentDate:["Appointment Date: ","የቀጠሮ ቀን"],
    invalidDate:["Invalid date given.","ልክ ያልሆነ ቀን አስገብተዋል።"],
    approveResponse:["Approve response","ምላሹን አጽድቅ"],
    noCaseFound:["This case isn't available","ጉዳዩ አልተገኘም"],
    currentProfile:["Current profile picture","የአሁኑ የመገለጫ ፎቶ"],
    newProfile:["New profile picture","አዲስ የመገለጫ ፎቶ"],
    createdInc:["Created","ተመዝግቧል"],
    forwardedInc:["Forwarded","ተመርቷል"],
    toColumn:["In how many columns should the receivers list be?","የተቀባይ ስም ዝርዝር በስንት ኮለመን ይሁን? "],
    ccColumn:["In how many columns should the Cc list be?","የግልባጭ ስም ዝርዝር በስንት ኮለመን ይሁን?"],
    forwardedByYou:["Forwarded by you","በእርስዎ ተመርቷል"],
    forwardedBy:["Forwarded by you","በእርሶዎ ተመርቷል"],
    notforwardedYou:["Not Forwarded","በእርሶዎ አልተመራም"],
    repliedByYou:["Replied by you","በእርሶዎ ተመልሷል"],
    replied:["Replied","በእርሶዎ ተመልሷል"],
    notReplied:["Not replied","በእርሶዎ አልተመለሰም"]
}